name: pull_request
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY_PR }}
          cache-read-only: true
      - name: :assemble
        run: ./gradlew assemble --stacktrace
      - name: :compileAllTests
        run: ./gradlew compileAllTests --stacktrace
      - name: :test
        run: ./gradlew test --stacktrace
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ZSON
          path: "build/libs/*.jar"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: "build/reports/tests/**"
